sudo: required
language: node_js
node_js:
- '8'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm test
notifications:
  webhooks:
    urls:
      - https://io.adafruit.com/api/v2/webhooks/feed/5CsxDuvUaA7eZdY741qc8Z5cpUBQ
    on_success: always
    on_failure: always
    on_start:   always
    on_error:   always